space_agencies = {
"Australia": ['🇦🇺', 'ASA' , 'Australian Space Agency', 'https://en.wikipedia.org/wiki/Australian_Space_Agency', 2018, 'https://www.industry.gov.au/strategies-for-the-future/australian-space-agency'],
"Belarus": ['🇧🇾', 'BSA', 'Belarus Space Agency', 'https://en.wikipedia.org/wiki/Belarus_Space_Agency', 2009, ''],
"Costa Rica": ['🇨🇷', 'ACAE', "Asociación Centroamericana de Aeronáutica y el Espacio", 'https://en.wikipedia.org/wiki/Central_American_Association_for_Aeronautics_and_Space', 2010, 'https://www.acae-ca.org'],
"Croatia": ['🇭🇷', 'HSA', 'Hrvatska Svemirska Agencija', 'https://en.wikipedia.org/wiki/Croatian_Space_Agency', 2007, ''],
"Mexico": ['🇲🇽', 'AEM', 'Agencia Espacial Mexicana', 'https://en.wikipedia.org/wiki/Agencia_Espacial_Mexicana', 2010, 'https://www.gob.mx/aem'],
"Algeria": ['🇩🇿', 'ASAL', 'الوكالة الفضائية الجزائرية', 'https://en.wikipedia.org/wiki/Algerian_Space_Agency', 2002, 'https://www.asal.dz'],
"International": ['', 'APSCO', '亚太空间合作组织', 'https://en.wikipedia.org/wiki/Asia-Pacific_Space_Cooperation_Organization', 2005, 'http://www.apsco.int/'],
"Austria": ['🇦🇹', 'ALR', 'Agentur für Luft- und Raumfahrt', 'https://en.wikipedia.org/wiki/Austrian_Space_Agency', 1972, 'https://www.ffg.at'],
"Azerbaijan": ['🇦🇿', 'AMAKA', 'Azərbaycan Milli Aerokosmik Agentliyinin', 'https://en.wikipedia.org/wiki/Azerbaijan_National_Aerospace_Agency', 1974, 'https://web.archive.org/web/20090922155709/http://www.science.az/en/amaka/agentlik/index.htm'],
"Bahrain": ['🇧🇭', 'NSSA', "Bahrain’s National Space Science Agency", 'https://en.wikipedia.org/wiki/Bahrain%E2%80%99s_National_Space_Science_Agency', 2014, 'https://www.nssa.gov.bh'],
"Belgium": ['🇧🇪', 'IASB', "Institut d’Aéronomie Spatiale de Belgique", 'https://en.wikipedia.org/wiki/Belgian_Institute_for_Space_Aeronomy', 1964, 'https://www.aeronomie.be'],
"Venezuela": ['🇻🇪', 'ABAE', 'Agencia Bolivariana para Actividades Espaciales', 'https://en.wikipedia.org/wiki/Bolivarian_Agency_for_Space_Activities', 2008, 'https://web.archive.org/web/20190103034749/http://abae.gob.ve/'],
"Brazil": ['🇧🇷', 'AEB', 'Agência Espacial Brasileira', 'https://en.wikipedia.org/wiki/Brazilian_Space_Agency', 1994, 'http://www.aeb.gov.br/'],
"United Kingdom": ['🇬🇧', 'UKSA', 'UK Space Agency', 'https://en.wikipedia.org/wiki/UK_Space_Agency', 2010, 'https://webarchive.nationalarchives.gov.uk/20100402172717/http%3A//www.ukspaceagency.bis.gov.uk/'],
"Bolivia": ['🇧🇴', 'ABE', 'Agencia Boliviana Espacial', 'https://en.wikipedia.org/wiki/Bolivian_Space_Agency', 2012, 'https://www.abe.bo'],
"Bulgaria": ['🇧🇬', 'ИКИ-БАН', ' Българска академия на науките', 'https://en.wikipedia.org/wiki/Bulgarian_Space_Agency', 1987, 'http://www.space.bas.bg/'],
"Canada": ['🇨🇦', 'CSA', 'Canadian Space Agency', 'https://en.wikipedia.org/wiki/Canadian_Space_Agency', 1989, 'https://www.asc-csa.gc.ca/eng/'],
"China": ['🇨🇳', 'CNSA', '国家航天局', 'https://en.wikipedia.org/wiki/China_National_Space_Administration', 1993, 'https://www.cnsa.gov.cn'],
"Colombia": ['🇨🇴', 'CCE', 'Comisión Colombiana del Espacio', 'https://en.wikipedia.org/wiki/Colombian_Space_Commission', 2006, 'https://web.archive.org/web/20120731122014/http://www.cce.gov.co/'],
"Singapore": ['🇸🇬', 'CRISP', 'Centre for Remote Imaging, Sensing and Processing', 'https://en.wikipedia.org/wiki/CRISP_NUS', 1995, 'https://www.crisp.nus.edu.sg'],
"International²": ['', 'CCSDS', 'Consultative Committee for Space Data Systems', 'https://en.wikipedia.org/wiki/Consultative_Committee_for_Space_Data_Systems', 1982, 'https://public.ccsds.org/default.aspx'],
"International³": ['', 'COSPAR', 'Committee on Space Research', 'https://en.wikipedia.org/wiki/COSPAR', 1958, 'https://web.archive.org/web/20080804051503/http://cosparhq.cnes.fr/'],
"Czech Republic": ['🇨🇿', 'MTCR', 'Ministerstvo dopravy České republiky', 'https://cs.wikipedia.org/wiki/Ministerstvo_dopravy_%C4%8Cesk%C3%A9_republiky', 2003, 'https://www.czechspaceportal.cz/EN/'],
"Denmark": ['🇩🇰', 'DRC', 'Danmarks Rumcenter', 'https://en.wikipedia.org/wiki/Danish_National_Space_Center', 1968, 'https://www.space.dtu.dk/english'],
"Denmark²": ['🇩🇰', 'DRKI', 'Dansk Rumforskningsinstitut', 'https://en.wikipedia.org/wiki/Danish_Space_Research_Institute', 2005, ''],
"ESA": ['', 'ESA', 'European Space Agency', 'https://en.wikipedia.org/wiki/European_Space_Agency', 1975, 'https://http://www.esa.int/'],
}
