quizzes = {
'moon': 'Most planets have at least one of this orbiting around.',
'black hole': "What comes in, never goes out.",
'sun': "Hot, hot, hot... It loves to be the center everything!.",
'elon musk': "He is a billionaire entrepreneur, philanthropist and visionary South-African-Canadian-American. Founder, CEO and CTO of SpaceX.",
'asteroid': 'Something fell from the sky and... R.I.P my fellow dinosaurs!',
"milky way": "Which galaxy is home to the Solar system?",
"pluto": "Which object lost its status as a planet in 2006?",
"a hypothetical reservoir for comets": "What is the Oort cloud?",
"venus": "What is the third brightest astronomical object in the sky?",
"2": "How many moons does Mars have?",
"galileo galilei": "Who discovered the four main moons of Jupiter in 1610?",
"polarity reverse of the sun": "What is the Solar Cycle?",
"a unit of measurement used to describe the expansion of the universe": "What is the Hubble constant?",
"helium": "Hydrogen and which other gas make up the majority of the Suns composition?",
"proxima centauri": "Which star is closest to the Sun?",
"asteroid": "Vesta is which type of heavenly body?",
"encke": "The comet with the shortest orbital period of 3.3 years is named what?",
"jupiter": "Which planet has the largest moon in the Solar system?",
"a highly magnetised rotating neutron star": "What is a pulsar?",
"4": "How many terrestrial planets are there in the Solar system?",
"88": "How many named constellations are there?",
"olympus mons": "What is the name of the largest volcano in the Solar system?",
"vega, deneb, altair": "Which three stars make the Summer Triangle?",
"eugene cernan": "Who was the last man on the Moon?",
"a powerful star explosion": "What is a supernova?",
"a measure of distance": "What is an astronomical unit?",
"a massive release of plasma from the sun": "What is a Coronal Mass Ejection?",
"2": "How many Ice giants are in the Solar system?",
"76 years": "What is the orbital period of Halley’s comet?",
"42km/s": "What is the escape velocity from the Solar system at the distance of Earth?",
"8": "How many planets there are in the Solar system?",
"hans lippershey": "Telescopes have significantly changed over time. Do you know who invented the first telescope though?",
"4": "How many planets with rings are there in our solar system?",
"180": "Approximately, how many moons are there in our solar system?",
"usually more expensive than reflecting telescopes": "Refractor telescopes are __",
"they could differentiate the planets from stars": "Before the first telescope was invented what were ancient astronomers able to learn about planets?",
"1975, venera 9": "When and which spacecraft did first send back surface images from a planet in our solar system?",
"venus": "Which was the first planet to be explored by a space probe?",
"606 days": "How long did it take for Pioneer 11 to reach Jupiter?",
"norton’s star atlas": "Which astronomy book for beginners was written by Ian Ridpath?",
"arthur c. clarke": "Who is the author of this famous quote: “I’m sure the universe is full of intelligent life. It’s just been too intelligent to come here.”"
}